sudo: false
dist: trusty

language: node_js
node_js: 8

notifications:
  email: false

cache:
  yarn: true
  directories:
    - ~/.nvm
    - ~/.cache
    - ./node_modules

before_install:
  - npm i -g yarn

install:
  - yarn install --frozen-lockfile

script:
  - true

after_success:
  - yarn travis-deploy-once "yarn semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
